<div class="pnav">
<ul class="container anchorsNav" id="home">
	<?php echo $this->displayMenu(); ?>
	<!-- <li class="kfgt"><a href="#konfig">KONFIGURER</a></li> -->
	<li class="left"><span class="priced"><?php echo $this->getStartingFrom(); ?></span></li>
	<!-- <li><a href="#specs">SPECIFIKATIONER</a></li> -->
	<!-- <li><a href="#reviews">ANMELDELSER</a></li> -->
	<!-- <li><a href="#benchmarks">BENCHMARKS</a></li> -->
	<!-- <li><a href="#gallery">GALLERI</a></li> -->
</ul>
</div>