<?php
$images = $this->getMediaGalleryImages();
?>
<div class="pgallery" id="gallery">
	<h4>Galleri</h4>
	
	<?php if (count($images) > 0): ?>
    <ul>
    <?php foreach ($images as $_image): ?>
        <li>
            <a href="/media/catalog/product<?php echo $_image->getFile(); ?>" rel="imageGallery" title="<?php echo $_image->getLabel(); ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->keepFrame(false)->resize(300); ?>" width="300" height="240" alt="<?php echo $_image->getLabel(); ?>" /><br />
            <h5><?php echo $_image->getLabel(); ?></h5></a>
        </li>
    <?php endforeach; ?>
    </ul>
	<?php endif; ?>

</div>

<script type="text/javascript">
jQuery(document).ready(function() {
    jQuery("a[rel=imageGallery]").fancybox({
        'titleShow' : 1,
        'transitionIn' : 'elastic',
        'transitionOut' : 'elastic'
    });
});
</script>